/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } fro./routes/dashboard/DashboardMainttings'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardDashboardMainRouteImport } from './components/dashboard/DashboardMain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardMainRoute = DashboardDashboardMainRouteImport.update({
  id: '/dashboard/DashboardMain',
  path: '/dashboard/DashboardMain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/DashboardMain': typeof DashboardDashboardMainRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/DashboardMain': typeof DashboardDashboardMainRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/DashboardMain': typeof DashboardDashboardMainRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/DashboardMain'
    | '/dashboard/customers'
    | '/dashboard/dashboard'
    | '/dashboard/leads'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/DashboardMain'
    | '/dashboard/customers'
    | '/dashboard/dashboard'
    | '/dashboard/leads'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard/DashboardMain'
    | '/dashboard/customers'
    | '/dashboard/dashboard'
    | '/dashboard/leads'
    | '/dashboard/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardDashboardMainRoute: typeof DashboardDashboardMainRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/DashboardMain': {
      id: '/dashboard/DashboardMain'
      path: '/dashboard/DashboardMain'
      fullPath: '/dashboard/DashboardMain'
      preLoaderRoute: typeof DashboardDashboardMainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardDashboardMainRoute: DashboardDashboardMainRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
